log: Err on non-options
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/log b/log
--- a/log
+++ b/log
@@ -13,7 +13,7 @@ for opt do
 		-g) mode=GREP; break ;;
 		--sk | --skim) selector='sk' ;;
 		--) break ;;
-		-*) echo >&2 "Error: unknown option: $opt" ;;
+		-*) echo >&2 "Error: unknown option: $opt"; exit 1 ;;
                 *) set -- "$@" "$opt";;
         esac
 done
