lore: Add --help text

diff --git a/lore b/lore
--- a/lore
+++ b/lore
@@ -11,6 +11,49 @@ else
 	reader=mutt
 fi
 
+show_help() {
+	[ $# -eq 0 ] || echo 2>^1 "Error: argument required"
+
+	cat >&2 <<"EOF"
+Usage: lore [options] [commitish or search query]
+
+Default search is by patchid of referenced commitish. Return full threads.
+  -s, --subject    search by commitish's subject line (no threads).
+  -q, --query      raw search questy with below query language (no threads).
+  -t, --thread     (force) return full threads.
+  -r, --results    (force) return of results only, without threads.
+  -T, --tags       Add -by tags for neomutt (works very slwoly.)
+
+Query language:
+    s:        match within Subject  e.g. s:"a quick brown fox"
+    d:        match date-time range, git "approxidate" formats supported
+              Open-ended ranges such as `d:last.week..' and
+              `d:..2.days.ago' are supported
+    b:        match within message body, including text attachments
+    nq:       match non-quoted text within message body
+    q:        match quoted text within message body
+    n:        match filename of attachment(s)
+    t:        match within the To header
+    c:        match within the Cc header
+    f:        match within the From header
+    a:        match within the To, Cc, and From headers
+    tc:       match within the To and Cc headers
+    l:        match contents of the List-Id header
+    bs:       match within the Subject and body
+    dfn:      match filename from diff
+    dfa:      match diff removed (-) lines
+    dfb:      match diff added (+) lines
+    dfhh:     match diff hunk header context (usually a function name)
+    dfctx:    match diff context lines
+    dfpre:    match pre-image git blob ID
+    dfpost:   match post-image git blob ID
+    dfblob:   match either pre or post-image git blob ID
+    patchid:  match `git patch-id --stable' output
+    rt:       match received time, like `d:' if sender's clock was correct
+EOF
+	exit ${1-0}
+}
+
 for opt; do
 	shift
 	case "$opt" in
@@ -21,12 +64,15 @@ for opt; do
 		-t | --thr*) force_mode="x=full+threads" ;;
 		-r | --res*) force_mode="z=results+only" ;;
 		-T | --tags) tags=y ;;
+		-h | --help) show_help ;;
 		-*) echo "unknown option: $opt"; exit 1 ;;
 		*) set -- "$@" "$opt" ;;
 	esac
 done
 
+[ $# -ne 0 ] || show_help 1
 commit=${1:?committish}
+
 for dir in . \
 	"$HOME/linux/torvalds" \
 	"$HOME/src/linux" \
